Controllers/CommentsController.cs
using AWS_ElasticBeanstalk_Project.Data;
using AWS_ElasticBeanstalk_Project.Models;
using Amazon.DynamoDBv2;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AWS_ElasticBeanstalk_Project.Controllers
{
    public class CommentsController : Controller
    {

        private IAmazonDynamoDB dynamoDBClient;

        private static string refVideoId = "";

        public CommentsController()
        {
            IAmazonDynamoDB dynamoDBClient = new AmazonDynamoDBClient(Amazon.RegionEndpoint.USEast1);
            //_context = context;
            this.dynamoDBClient = dynamoDBClient;
        }

        // GET: Comments
        public async Task<IActionResult> Index(string videoId, string userId)
        {
            //string videoId = "";
            refVideoId = videoId;
            DynamoDBServices service = new DynamoDBServices(dynamoDBClient);

            if (string.IsNullOrEmpty(videoId))
            {
                return RedirectToAction("Index", "Videos");
            }

            Video video = await service.GetVideoAsync(videoId);

            if (string.IsNullOrEmpty(userId))
            {
                ViewData["userId"] = "";
            }
            else
            {
                ViewData["userId"] = userId;
            }

            if (string.IsNullOrEmpty(videoId))
            {
                ViewData["videoId"] = "";
            }
            else
            {
                ViewData["videoId"] = videoId;
            }

            return View(video.Comments);

        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(string id, string videoId, string userId)
        {
            bool commentFound = false;
            Comment detailComment = new Comment();

            if (string.IsNullOrEmpty(userId))
            {
                ViewData["userId"] = "";
            }
            else
            {
                ViewData["userId"] = userId;
            }

            if (string.IsNullOrEmpty(videoId))
            {
                ViewData["videoId"] = "";
            }
            else
            {
                ViewData["videoId"] = videoId;
            }

            if (id == null)
            {
                return NotFound();
            }

            DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
            Video video = await service.GetVideoAsync(refVideoId);

            if (video == null)
            {
                return NotFound();
            }


            foreach (Comment comment in video.Comments)
            {
                if (comment.CommentId == id)
                {
                    commentFound = true;
                    detailComment = comment;
                }
            }

            if (commentFound == false)
            {
                return NotFound();
            }

            return View(detailComment);
        }

        // GET: Comments/Create
        public IActionResult Create(string videoId, string userId)
        {
            string hjh = (string)ViewData["userId"];

            if (string.IsNullOrEmpty(userId))
            {
                ViewData["userId"] = "";
            }
            else
            {
                ViewData["userId"] = userId;
            }

            if (string.IsNullOrEmpty(videoId))
            {
                ViewData["videoId"] = "";
            }
            else
            {
                ViewData["videoId"] = videoId;
            }
            return View();
        }

        // POST: Comments/Create
 
        [HttpPost]
        [ValidateAntiForgeryToken]


        public async Task<IActionResult> Create([Bind("CommentId, Rating, UserId, CommentContent")] Comment newComment)
        {
            if (ModelState.IsValid)
            {
                DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
                Video video = await service.GetVideoAsync(refVideoId);

                newComment.CommentId = System.Guid.NewGuid().ToString();
                newComment.UserId = "1";

                if (video.Comments == null)
                {
                    video.Comments = new List<Comment>();
                }

                video.Comments.Add(newComment);

                decimal overallRating = 0;

                foreach (Comment comment in video.Comments)
                {
                    overallRating += comment.Rating;
                }

                video.OverallRating = Math.Truncate(overallRating / video.Comments.Count);

                //DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
                Video updatedVideo = await service.UpdateVideoAsync(video);
                return RedirectToAction("Index");
            }
            return View(newComment);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(string id, string videoId, string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                ViewData["userId"] = "";
            }
            else
            {
                ViewData["userId"] = userId;
            }

            if (string.IsNullOrEmpty(videoId))
            {
                ViewData["videoId"] = "";
            }
            else
            {
                ViewData["videoId"] = videoId;
            }

            if (id == null)
            {
                return NotFound();
            }

            Comment detailComment = new Comment();

            DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
            Video video = await service.GetVideoAsync(refVideoId);

            if (video == null)
            {
                return NotFound();
            }


            foreach (Comment comment in video.Comments)
            {
                if (comment.CommentId == id)
                {
                    detailComment = comment;
                    return View(detailComment);
                }
            }

            return View(detailComment);
        }

        // POST: Books/Edit/5
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CommentId, Rating, UserId, CommentContent")] Comment updatedComment)
        {
            if (id != updatedComment.CommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
                    Video video = await service.GetVideoAsync(refVideoId);

                    updatedComment.UserId = "1";

                    for (int i = 0; i < video.Comments.Count; i++)
                    {
                        if (video.Comments[i].CommentId == id)
                        {
                            video.Comments[i] = updatedComment;
                        }
                    }

                    decimal overallRating = 0;

                    foreach (Comment comment in video.Comments)
                    {
                        overallRating += comment.Rating;
                    }

                    video.OverallRating = Math.Truncate(overallRating / video.Comments.Count);

                    Video updatedVideo = await service.UpdateVideoAsync(video);

                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction("Index");
            }
            return View(updatedComment);
        }

        public async Task<IActionResult> Delete(string id)
        {
            //if (string.IsNullOrEmpty(userId))
            //{
            //    ViewData["userId"] = "";
            //}
            //else
            //{
            //    ViewData["userId"] = userId;
            //}

            //if (string.IsNullOrEmpty(videoId))
            //{
            //    ViewData["videoId"] = "";
            //}
            //else
            //{
            //    ViewData["videoId"] = videoId;
            //}

            if (id == null)
            {
                return NotFound();
            }


            DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
            Video video = await service.GetVideoAsync(refVideoId);
            Comment detailComment = new Comment();


            if (video == null)
            {
                return NotFound();
            }

            foreach (Comment comment in video.Comments)
            {
                if (comment.CommentId == id)
                {
                    detailComment = comment;
                    return View(detailComment);
                }
            }

            return View(detailComment);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            DynamoDBServices service = new DynamoDBServices(dynamoDBClient);
            Video video = await service.GetVideoAsync(refVideoId);

            for (int i = 0; i < video.Comments.Count; i++)
            {
                if (video.Comments[i].CommentId == id)
                {
                    video.Comments.RemoveAt(i);
                }
            }

            decimal overallRating = 0;

            foreach (Comment comment in video.Comments)
            {
                overallRating += comment.Rating;
            }

            video.OverallRating = Math.Truncate(overallRating / video.Comments.Count);

            Video updatedVideo = await service.UpdateVideoAsync(video);

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Comments/Create.cshtml
@model AWS_ElasticBeanstalk_Project.Models.Comment
@{
    ViewData["Title"] = "Create";
    var userId = ViewData["userId"].ToString();
    var videoId = ViewData["videoId"].ToString();
}

<h2>Create</h2>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label">Rating</label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommentContent" class="control-label">Comment</label>
                <input asp-for="CommentContent" class="form-control" />
                <span asp-validation-for="CommentContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index", "Comments", new { userId = @userId, videoId = @videoId })
    @*<a asp-action="Index">Back to List</a>*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comments/Delete.cshtml
@model AWS_ElasticBeanstalk_Project.Models.Comment

@{
    ViewData["Title"] = "Delete";
    var userId = ViewData["userId"].ToString();
    var videoId = ViewData["videoId"].ToString();
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <a href="C:\Users\saura\Downloads\Semester-03_Files\API Engineering & Cloud Computing\Assignments\301109394(sharma)_Lab03\301109394(sharma)_Lab03\Views\Comments\Delete.cshtml">C:\Users\saura\Downloads\Semester-03_Files\API Engineering & Cloud Computing\Assignments\301109394(sharma)_Lab03\301109394(sharma)_Lab03\Views\Comments\Delete.cshtml</a>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CommentContent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CommentContent)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CommentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.ActionLink("Back to List", "Index", "Comments", new { userId = @userId, videoId = @videoId })
        @*<a asp-action="Index">Back to List</a>*@
    </form>
</div>

Views/Comments/Details.cshtml
@model AWS_ElasticBeanstalk_Project.Models.Comment
@{
    ViewData["Title"] = "Details";
    var userId = ViewData["userId"].ToString();
    var videoId = ViewData["videoId"].ToString();
}

<h2>Details</h2>

<div>
    <h4>Comment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CommentContent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CommentContent)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", "Comments", new { id = @Model.CommentId, userId = @userId, videoId = @videoId }) |
    @Html.ActionLink("Back to List", "Index", "Comments", new { userId = @userId, videoId = @videoId })
    @*<a asp-action="Edit" asp-route-id="@Model.CommentId">Edit</a> |
        <a asp-action="Index">Back to List</a>*@
</div>

Views/Comments/Edit.cshtml
@model AWS_ElasticBeanstalk_Project.Models.Comment

@{
    ViewData["Title"] = "Edit";
    var userId = ViewData["userId"].ToString();
    var videoId = ViewData["videoId"].ToString();
}
}

<h2>Edit</h2>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CommentId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label">Rating</label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CommentContent" class="control-label">Comment</label>
                <input asp-for="CommentContent" class="form-control" />
                <span asp-validation-for="CommentContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index", "Comments", new { userId = @userId, videoId = @videoId }) |
    @*<a asp-action="Index">Back to List</a>*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Comments/Index.cshtml
@model IEnumerable<AWS_ElasticBeanstalk_Project.Models.Comment>
@{
    ViewData["Title"] = "Index";
    var userId = ViewData["userId"].ToString();
    var videoId = ViewData["videoId"].ToString();
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    @Html.ActionLink("Create New", "Create", "Comments", new { videoId = @videoId, userId = @userId }) |
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CommentId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CommentContent)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CommentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CommentContent)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>